# Generated by Django 5.1.4 on 2024-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
